#!/usr/bin/env python3
"""Generate an ECDSA P-256 key pair for OTA firmware manifest signing.

Produces:
  - <name>.key     Private key (PEM) — keep secret, never embed in firmware.
  - <name>.pub     Public key (PEM) — embed in firmware via OTA_VERIFY_PUBKEY_PEM.
  - <name>.h       C header fragment for build flag / direct inclusion.

Usage:
    python tools/ota_keygen.py [--name ota_release]
"""

import argparse
import subprocess
import sys

def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                  formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--name", default="ota_release",
                    help="base filename for the key pair (default: ota_release)")
    args = ap.parse_args()

    priv_path = f"{args.name}.key"
    pub_path = f"{args.name}.pub"
    header_path = f"{args.name}.h"

    # Generate private key.
    r = subprocess.run(["openssl", "ecparam", "-genkey", "-name", "prime256v1",
                        "-noout", "-out", priv_path], capture_output=True)
    if r.returncode != 0:
        print(f"openssl ecparam failed: {r.stderr.decode()}", file=sys.stderr)
        return 1

    # Extract public key.
    r = subprocess.run(["openssl", "ec", "-in", priv_path, "-pubout",
                        "-out", pub_path], capture_output=True)
    if r.returncode != 0:
        print(f"openssl ec failed: {r.stderr.decode()}", file=sys.stderr)
        return 1

    pub_pem = open(pub_path).read().strip()
    print(f"private key: {priv_path}")
    print(f"public key:  {pub_path}")

    # Write C header fragment.
    escaped = pub_pem.replace("\n", "\\n\" \\\n  \"")
    with open(header_path, "w") as f:
        f.write(f'// Generated by tools/ota_keygen.py — embed in build flags or include directly.\n')
        f.write(f'#define OTA_VERIFY_PUBKEY_PEM \\\n')
        f.write(f'  "{escaped}\\n"\n')
    print(f"C fragment:  {header_path}")
    print(f"\nAdd to build flags: -include {header_path}")
    print(f"Or paste the #define into your platformio.ini / build_flags.")
    return 0

if __name__ == "__main__":
    sys.exit(main())
